services:
  - type: web
    runtime: node
    name: bird-ticker
    region: frankfurt
    plan: free
    rootDir: ./
    buildCommand: cd proxy && npm ci --production
    startCommand: node proxy/server.js
    envVars:
      - key: NODE_ENV
        value: production
